version: '3'

services:
  mariadb:
    container_name: mariadb-container
    build: ./requirements/mariadb
    image: debian:buster
    restart: always
    expose:
      - "3306"
    networks:
      - intra
    tty: true
    env_file: .env
    volumes:
      - data:/var/lib/mysql
  nginx:
    container_name: nginx-container
    build: ./requirements/nginx
    image: debian:buster
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    networks:
      - intra
    tty: true
    env_file: .env
  wordpress:
    container_name: wordpress-container
    build: ./requirements/wordpress
    image: debian:buster
    restart: always
    expose:
      - "9000"
    networks:
      - intra
    tty: true
    env_file: .env
    volumes:
      - data:/var/www/html
networks:
  intra:
    driver: bridge
volumes:
  data: /home/hyungjpa/data