services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    tty: true
    networks:
      - my-network

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    tty: true
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - my-network
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    restart: always
    expose:
      - "9000"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - my-network
    depends_on:
      - mariadb

networks:
  my-network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ./data/mariadb
      # device: /home/hyungjpa/data/mariadb
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ./data/wordpress
      # device: /home/hyungjpa/data/wordpress
      o: bind